import time
import pytest

from maanaksetu.adapters.dossier import compile_dossier, compute_audit_digest
from maanaksetu.domain.models import (
    AuditResult,
    AuditSummary,
    DocumentSegment,
    Evidence,
    Finding,
)
from maanaksetu.domain.states import DecisionState, GateStatus, ReviewState, Severity, ViolationType


@pytest.fixture
def sample_audit_result() -> AuditResult:
    """Provide a realistic AuditResult with findings and evidence."""
    evidence = Evidence(
        finding_id="fnd-01",
        rule_id="RULE-LIFECYCLE-OBSOLETE",
        knowledge_fact_ref="standards_catalog(IS 269:1989)",
        requirement_ref="req-01",
        source_segment_ref="seg-01",
        statutory_or_technical_basis="BIS Act 2016 Section 13 & Gazette S.O. 3177(E)",
        fact_payload={"status": "WITHDRAWN", "superseded_by": "IS 269:2015"},
        source_segment_text="53 Grade Ordinary Portland Cement strictly conforming to IS 269:1989",
    )

    finding = Finding(
        finding_id="fnd-01",
        requirement_id="req-01",
        segment_id="seg-01",
        rule_id="RULE-LIFECYCLE-OBSOLETE",
        violation_type=ViolationType.ERR_OBSOLETE_STANDARD,
        severity=Severity.CRITICAL,
        decision_state=DecisionState.VIOLATION,
        review_state=ReviewState.NOT_APPLICABLE,
        detected_entity="IS 269:1989",
        statutory_basis="BIS Act 2016 Section 13 & Gazette S.O. 3177(E)",
        replacement_standard="IS 269:2015",
        recommended_remediation="Update statutory citation from obsolete 'IS 269:1989' to active 'IS 269:2015'.",
        engineering_rationale="Clause cites withdrawn standard IS 269:1989 superseded by IS 269:2015.",
        segment_text="53 Grade Ordinary Portland Cement strictly conforming to IS 269:1989",
        evidence=evidence,
    )

    result = AuditResult(
        document_id="NHAI-TND-2024-001",
        document_title="NHAI Highway Expansion Phase IV Specification",
        gate_status=GateStatus.STATUTORY_NON_COMPLIANT,
        total_segments_analyzed=1,
        findings=[finding],
        cascading_dependency_alerts=[],
        summary=AuditSummary(
            total_requirements_evaluated=1,
            conformant_requirements=0,
            critical_violations=1,
            high_violations=0,
            medium_violations=0,
            pending_reviews=0,
        ),
    )
    result.sha256_digest = compute_audit_digest(result)
    return result


def test_dossier_compilation(sample_audit_result: AuditResult):
    """Verify that Typst compiles an authentic 3-page audit dossier in < 250ms."""
    start = time.perf_counter()
    pdf_bytes = compile_dossier(sample_audit_result)
    duration_ms = (time.perf_counter() - start) * 1000.0

    assert len(pdf_bytes) > 1000, "PDF bytes should be non-empty"
    assert pdf_bytes.startswith(b"%PDF-"), "Output must be valid PDF"
    assert b"%%EOF" in pdf_bytes, "Output must have valid PDF trailer"

    # Verify 3 pages generated by inspecting Pages catalog dictionary
    assert b"/Type/Pages/Count 3" in pdf_bytes or b"/Count 3" in pdf_bytes, "Dossier must be strictly 3 pages"
    assert len(pdf_bytes) > 50000, f"Dossier must be publication grade with embedded assets (got {len(pdf_bytes)} bytes)"

    print(f"\nDossier compiled successfully in {duration_ms:.2f} ms")
